
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.enum.shapes import MSO_SHAPE
from pptx.dml.color import RGBColor
import io
import plotly.io as pio

def create_presentation(kpi_data, chart_figures=None, table_data=None):
    """
    Generates a PowerPoint presentation with editable KPI cards, chart images, and data tables.
    
    Args:
        kpi_data (list): List of dicts [{'title': '...', 'value': '...', 'trend': '...'}]
        chart_figures (dict): Dict of {title: plotly_fig} objects.
        table_data (dict): Dict of {title: {'columns': [], 'rows': []}} objects.
    
    Returns:
        BytesIO: The PPTX file in memory.
    """
    prs = Presentation()
    
    # --- SLIDE 1: Title ---
    slide_layout = prs.slide_layouts[0] # Title Slide
    slide = prs.slides.add_slide(slide_layout)
    title = slide.shapes.title
    subtitle = slide.placeholders[1]
    
    title.text = "Enterprise Intelligence Suite"
    subtitle.text = "Executive Dashboard Report\nGenerated by Reflex"
    
    # --- SLIDE 2: Business KPI Summary ---
    # (Existing KPI Logic...)
    slide_layout = prs.slide_layouts[5] # Blank
    slide = prs.slides.add_slide(slide_layout)
    
    # Slide Title
    title_shape = slide.shapes.add_textbox(Inches(0.5), Inches(0.2), Inches(9), Inches(1))
    tf = title_shape.text_frame
    tf.text = "Business Summary - Key Performance Indicators"
    tf.paragraphs[0].font.size = Pt(24)
    tf.paragraphs[0].font.bold = True
    
    # Create Grid for KPIs
    # Determine layout based on count
    # If <= 6: 3 cols x 2 rows
    # If > 6: use smaller boxes or more rows
    count = len(kpi_data)
    cols = 3
    rows = (count + cols - 1) // cols
    
    start_x = 0.5
    start_y = 1.2
    
    # Adjust size if many rows
    height = 1.5 if rows <= 2 else 1.2
    
    width = 2.8
    gap_x = 0.2
    gap_y = 0.2
    
    for i, kpi in enumerate(kpi_data):
        row = i // cols
        col = i % cols
        
        # If too many items, prevent overflow (simple limit)
        if row > 3: break 
        
        x = Inches(start_x + (col * (width + gap_x)))
        y = Inches(start_y + (row * (height + gap_y)))
        
        # 1. Card Background
        shape = slide.shapes.add_shape(
            MSO_SHAPE.ROUNDED_RECTANGLE, x, y, Inches(width), Inches(height)
        )
        shape.fill.solid()
        shape.fill.fore_color.rgb = RGBColor(245, 245, 245)
        shape.line.color.rgb = RGBColor(200, 200, 200)
        
        # 2. KPI Title
        text_box = slide.shapes.add_textbox(x, y + Inches(0.1), Inches(width), Inches(0.3))
        tf = text_box.text_frame
        p = tf.paragraphs[0]
        p.text = kpi.get("label", "Metric")
        p.font.size = Pt(10)
        p.font.color.rgb = RGBColor(100, 100, 100)
        p.alignment = 1 
        
        # 3. KPI Value
        value_box = slide.shapes.add_textbox(x, y + Inches(0.4), Inches(width), Inches(0.5))
        tf = value_box.text_frame
        p = tf.paragraphs[0]
        p.text = str(kpi.get("value", "0"))
        p.font.size = Pt(20) if rows > 2 else Pt(24) # Shrink if many
        p.font.bold = True
        p.font.color.rgb = RGBColor(0, 0, 0)
        
        # 4. Trend
        trend = kpi.get("trend", "")
        if trend:
            trend_box = slide.shapes.add_textbox(x, y + Inches(height - 0.4), Inches(width), Inches(0.3))
            tf = trend_box.text_frame
            p = tf.paragraphs[0]
            p.text = trend
            p.font.size = Pt(10)
            if "-" in trend or "↓" in trend:
                p.font.color.rgb = RGBColor(200, 0, 0) # Red
            else:
                p.font.color.rgb = RGBColor(0, 150, 0) # Green

    # --- SLIDES 3+: Tables ---
    if table_data:
        for title, data in table_data.items():
            slide_layout = prs.slide_layouts[5] # Blank
            slide = prs.slides.add_slide(slide_layout)
            
            # Title
            title_shape = slide.shapes.add_textbox(Inches(0.5), Inches(0.2), Inches(9), Inches(1))
            tf = title_shape.text_frame
            tf.text = title
            tf.paragraphs[0].font.size = Pt(24)
            tf.paragraphs[0].font.bold = True
            
            columns = data.get("columns", [])
            rows = data.get("rows", [])
            
            if not columns or not rows:
                continue
                
            # Create Table
            rows_count = len(rows) + 1 # +1 for header
            cols_count = len(columns)
            
            # Paging if too long? 
            # For now, simplistic rendering (first 15 rows)
            MAX_ROWS = 15
            if rows_count > MAX_ROWS + 1:
                display_rows = rows[:MAX_ROWS]
                rows_count = MAX_ROWS + 1
            else:
                display_rows = rows
            
            left = Inches(0.5)
            top = Inches(1.2)
            width = Inches(9)
            height = Inches(0.8) # initial height, grows
            
            shape = slide.shapes.add_table(rows_count, cols_count, left, top, width, height)
            table = shape.table
            
            # Header
            for i, col_name in enumerate(columns):
                cell = table.cell(0, i)
                cell.text = str(col_name)
                cell.fill.solid()
                cell.fill.fore_color.rgb = RGBColor(50, 50, 50) # Dark header
                cell.text_frame.paragraphs[0].font.color.rgb = RGBColor(255, 255, 255)
                cell.text_frame.paragraphs[0].font.bold = True
            
            # Body
            for r_idx, row_data in enumerate(display_rows):
                # row_data should be a list of values
                for c_idx, val in enumerate(row_data):
                    # Safety check
                    if c_idx < cols_count:
                        cell = table.cell(r_idx + 1, c_idx)
                        cell.text = str(val)
                        cell.text_frame.paragraphs[0].font.size = Pt(10)
                        
                        # Alternating row color
                        if r_idx % 2 == 0:
                            cell.fill.solid()
                            cell.fill.fore_color.rgb = RGBColor(240, 240, 240)

    # --- SLIDES 4+: Charts ---
    if chart_figures:
        for title, fig in chart_figures.items():
            slide_layout = prs.slide_layouts[5] # Blank
            slide = prs.slides.add_slide(slide_layout)
            
            # Title
            title_shape = slide.shapes.add_textbox(Inches(0.5), Inches(0.2), Inches(9), Inches(1))
            tf = title_shape.text_frame
            tf.text = f"Analysis: {title}"
            tf.paragraphs[0].font.size = Pt(24)
            
            # Convert Plotly Element to Image
            try:
                # fig is a plotly Graph Object
                img_bytes = pio.to_image(fig, format='png', width=1000, height=600, scale=2)
                image_stream = io.BytesIO(img_bytes)
                
                # Add Image to Slide
                slide.shapes.add_picture(image_stream, Inches(0.5), Inches(1.5), Inches(9), Inches(5))
            except Exception as e:
                err_box = slide.shapes.add_textbox(Inches(1), Inches(3), Inches(8), Inches(1))
                err_box.text = f"Error generating chart image: {e}\n(Make sure kaleido is installed)"

    output = io.BytesIO()
    prs.save(output)
    output.seek(0)
    return output
